package com.boco.customer.field;

public interface S1uS11 {
	int S1U_S11_LEN = 36;
	int LENGTH=0;
	int CITY=1;
	int INTERFACE=2;
	int XDR_ID=3;
	int RAT=4;
	int IMSI=5;
	int IMEI=6;
	int MSISDN=7;
	int PROCEDURE_TYPE=8;
	int PROCEDURE_STRAT_TIME=9;
	int PROCEDURE_END_TIME=10;
	int PROCEDURE_STATUS=11;
	int FAILURE_CAUSE=12;
	int REQUEST_CAUSE=13;
	int USER_IPV4=14;
	int USER_IPV6=15;
	int MME_ADDRESS=16;
	int SGWOROLD_MME_ADDRESS=17;
	int MME_PORT=18;
	int SGWOROLD_MME_PORT=19;
	int MME_CONTROL_TEID=20;
	int OLDMMEORSGW_CONTROL_TEID=21;
	int APN=22;
	int EPS_BEARER_CNT=23;
	int BEARER1ID=24;
	int BEARER1TYPE=25;
	int BEARER1QCI=26;
	int BEARER1STATUS=27;
	int BEARER1ENB_GTP_TEID=28;
	int BEARER1SGW_GTP_TEID=29;
	int BEARER2ID=30;
	int BEARER2TYPE=31;
	int BEARER2QCI=32;
	int BEARER2STATUS=33;
	int BEARER2ENB_GTP_TEID=34;
	int BEARER2SGW_GTP_TEID=35;
}

