package com.boco.customer.fieldZx;

import java.util.ArrayList;
import java.util.List;
import java.util.regex.Pattern;

public class S1MmeZx {
	private int TIME_ID=3;
	private int LENGTH=4;
	private int CITY=5;
	private int INTERFACE=6;
	private int XDR_ID=7;
	private int RAT=8;
	private int IMSI=9;
	private int IMEI=10;
	private int MSISDN=11;
	private int PROCEDURE_TYPE=16;
	private int PROCEDURE_STRAT_TIME=17;
	private int PROCEDURE_END_TIME=18;
	private int PROCEDURE_STATUS=19;
	private int REQUEST_CAUSE=20;
	private int FAILURE_CAUSE=21;
	private int KEYWORD1=24;
	private int KEYWORD2=25;
	private int KEYWORD3=26;
	private int KEYWORD4=27;
	private int MME_UE_S1AP_ID=28;
	private int OLD_MME_GROUP_ID=29;
	private int OLD_MME_CODE=30;
	private int OLDM_TMSI=31;
	private int MMEGROUPID=32;
	private int MMECODE=33;
	private int M_TMSI=34;
	private int UE_IP_ADD_TYPE=35;
	private int USER_IP=36;
	private int MACHINE_IP_ADD_TYPE=37;
	private int MME_IP_ADD=38;
	private int ENB_IP_ADD=41;
	private int MME_PORT=42;
	private int ENB_PORT=43;
	private int TAC=44;
	private int CELL_ID=45;
	private int OTHER_TAC=61;
	private int OTHER_ECI=62;
	private int APN=63;
	private int EPS_BEARER_CNT=64;
	private int BEARER1ID=65;
	private int BEARER1TYPE=66;
	private int BEARER1QCI=67;
	private int BEARER1STATUS=68;
	private int BEARER1REQUESTCAUSE=69;
	private int BEARER1FAILURECAUSE=70;
	private int BEARER1ENBGTP_TEID=71;
	private int BEARER1SGWGTP_TEID=72;
	private int BEARER2ID=73;
	private int BEARER2TYPE=74;
	private int BEARER2QCI=75;
	private int BEARER2STATUS=76;
	private int BEARER2REQUESTCAUSE=77;
	private int BEARER2FAILURECAUSE=78;
	private int BEARER2ENBGTP_TEID=79;
	private int BEARER2SGWGTP_TEID=80;
	private int BEARER3ID=81;
	private int BEARER3TYPE=82;
	private int BEARER3QCI=83;
	private int BEARER3STATUS=84;
	private int BEARER3REQUESTCAUSE=85;
	private int BEARER3FAILURECAUSE=86;
	private int BEARER3ENBGTP_TEID=87;
	private int BEARER3SGWGTP_TEID=88;
	private int BEARER4ID=89;
	private int BEARER4TYPE=90;
	private int BEARER4QCI=91;
	private int BEARER4STATUS=92;
	private int BEARER4REQUESTCAUSE=93;
	private int BEARER4FAILURECAUSE=94;
	private int BEARER4ENBGTP_TEID=95;
	private int BEARER4SGWGTP_TEID=96;
	private int BEARER5ID=97;
	private int BEARER5TYPE=98;
	private int BEARER5QCI=99;
	private int BEARER5STATUS=100;
	private int BEARER5REQUESTCAUSE=101;
	private int BEARER5FAILURECAUSE=102;
	private int BEARER5ENBGTP_TEID=103;
	private int BEARER5SGWGTP_TEID=104;
	private int BEARER6ID=105;
	private int BEARER6TYPE=106;
	private int BEARER6QCI=107;
	private int BEARER6STATUS=108;
	private int BEARER6REQUESTCAUSE=109;
	private int BEARER6FAILURECAUSE=110;
	private int BEARER6ENBGTP_TEID=111;
	private int BEARER6SGWGTP_TEID=112;
	private int BEARER7ID=113;
	private int BEARER7TYPE=114;
	private int BEARER7QCI=115;
	private int BEARER7STATUS=116;
	private int BEARER7REQUESTCAUSE=117;
	private int BEARER7FAILURECAUSE=118;
	private int BEARER7ENBGTP_TEID=119;
	private int BEARER7SGWGTP_TEID=120;
	private int BEARER8ID=121;
	private int BEARER8TYPE=122;
	private int BEARER8QCI=123;
	private int BEARER8STATUS=124;
	private int BEARER8REQUESTCAUSE=125;
	private int BEARER8FAILURECAUSE=126;
	private int BEARER8ENBGTP_TEID=127;
	private int BEARER8SGWGTP_TEID=128;
	private int BEARER9ID=129;
	private int BEARER9TYPE=130;
	private int BEARER9QCI=131;
	private int BEARER9STATUS=132;
	private int BEARER9REQUESTCAUSE=133;
	private int BEARER9FAILURECAUSE=134;
	private int BEARER9ENBGTP_TEID=135;
	private int BEARER9SGWGTP_TEID=136;
	
	
	private static Pattern pattern = Pattern.compile("\\|");
	public List<String> ReturnListZx(List<String> list)
	{
		
		List<String> list_zx =new ArrayList<String>();
		for(String lines:list)
		{
			
			String[] xdrdata = pattern.split(lines.toString(), -1);
			StringBuffer sb = new StringBuffer();
			sb.append(xdrdata[TIME_ID]).append("|");
			sb.append(xdrdata[LENGTH]).append("|");
			sb.append(xdrdata[CITY]).append("|");
			sb.append(xdrdata[INTERFACE]).append("|");
			sb.append(xdrdata[XDR_ID]).append("|");
			sb.append(xdrdata[RAT]).append("|");
			sb.append(xdrdata[IMSI]).append("|");
			sb.append(xdrdata[IMEI]).append("|");
			sb.append(xdrdata[MSISDN]).append("|");
			sb.append(xdrdata[PROCEDURE_TYPE]).append("|");
			sb.append(xdrdata[PROCEDURE_STRAT_TIME]).append("|");
			sb.append(xdrdata[PROCEDURE_END_TIME]).append("|");
			sb.append(xdrdata[PROCEDURE_STATUS]).append("|");
			sb.append(xdrdata[REQUEST_CAUSE]).append("|");
			sb.append(xdrdata[FAILURE_CAUSE]).append("|");
			sb.append(xdrdata[KEYWORD1]).append("|");
			sb.append(xdrdata[KEYWORD2]).append("|");
			sb.append(xdrdata[KEYWORD3]).append("|");
			sb.append(xdrdata[KEYWORD4]).append("|");
			sb.append(xdrdata[MME_UE_S1AP_ID]).append("|");
			sb.append(xdrdata[OLD_MME_GROUP_ID]).append("|");
			sb.append(xdrdata[OLD_MME_CODE]).append("|");
			sb.append(xdrdata[OLDM_TMSI]).append("|");
			sb.append(xdrdata[MMEGROUPID]).append("|");
			sb.append(xdrdata[MMECODE]).append("|");
			sb.append(xdrdata[M_TMSI]).append("|");
			sb.append(xdrdata[UE_IP_ADD_TYPE]).append("|");
			sb.append(xdrdata[USER_IP]).append("|");
			sb.append(xdrdata[MACHINE_IP_ADD_TYPE]).append("|");
			sb.append(xdrdata[MME_IP_ADD]).append("|");
			sb.append(xdrdata[ENB_IP_ADD]).append("|");
			sb.append(xdrdata[MME_PORT]).append("|");
			sb.append(xdrdata[ENB_PORT]).append("|");
			sb.append(xdrdata[TAC]).append("|");
			sb.append(xdrdata[CELL_ID]).append("|");
			sb.append(xdrdata[OTHER_TAC]).append("|");
			sb.append(xdrdata[OTHER_ECI]).append("|");
			sb.append(xdrdata[APN]).append("|");
			sb.append(xdrdata[EPS_BEARER_CNT]).append("|");
			sb.append(xdrdata[BEARER1ID]).append("|");
			sb.append(xdrdata[BEARER1TYPE]).append("|");
			sb.append(xdrdata[BEARER1QCI]).append("|");
			sb.append(xdrdata[BEARER1STATUS]).append("|");
			sb.append(xdrdata[BEARER1REQUESTCAUSE]).append("|");
			sb.append(xdrdata[BEARER1FAILURECAUSE]).append("|");
			sb.append(xdrdata[BEARER1ENBGTP_TEID]).append("|");
			sb.append(xdrdata[BEARER1SGWGTP_TEID]).append("|");
			sb.append(xdrdata[BEARER2ID]).append("|");
			sb.append(xdrdata[BEARER2TYPE]).append("|");
			sb.append(xdrdata[BEARER2QCI]).append("|");
			sb.append(xdrdata[BEARER2STATUS]).append("|");
			sb.append(xdrdata[BEARER2REQUESTCAUSE]).append("|");
			sb.append(xdrdata[BEARER2FAILURECAUSE]).append("|");
			sb.append(xdrdata[BEARER2ENBGTP_TEID]).append("|");
			sb.append(xdrdata[BEARER2SGWGTP_TEID]).append("|");
			sb.append(xdrdata[BEARER3ID]).append("|");
			sb.append(xdrdata[BEARER3TYPE]).append("|");
			sb.append(xdrdata[BEARER3QCI]).append("|");
			sb.append(xdrdata[BEARER3STATUS]).append("|");
			sb.append(xdrdata[BEARER3REQUESTCAUSE]).append("|");
			sb.append(xdrdata[BEARER3FAILURECAUSE]).append("|");
			sb.append(xdrdata[BEARER3ENBGTP_TEID]).append("|");
			sb.append(xdrdata[BEARER3SGWGTP_TEID]).append("|");
			sb.append(xdrdata[BEARER4ID]).append("|");
			sb.append(xdrdata[BEARER4TYPE]).append("|");
			sb.append(xdrdata[BEARER4QCI]).append("|");
			sb.append(xdrdata[BEARER4STATUS]).append("|");
			sb.append(xdrdata[BEARER4REQUESTCAUSE]).append("|");
			sb.append(xdrdata[BEARER4FAILURECAUSE]).append("|");
			sb.append(xdrdata[BEARER4ENBGTP_TEID]).append("|");
			sb.append(xdrdata[BEARER4SGWGTP_TEID]).append("|");
			sb.append(xdrdata[BEARER5ID]).append("|");
			sb.append(xdrdata[BEARER5TYPE]).append("|");
			sb.append(xdrdata[BEARER5QCI]).append("|");
			sb.append(xdrdata[BEARER5STATUS]).append("|");
			sb.append(xdrdata[BEARER5REQUESTCAUSE]).append("|");
			sb.append(xdrdata[BEARER5FAILURECAUSE]).append("|");
			sb.append(xdrdata[BEARER5ENBGTP_TEID]).append("|");
			sb.append(xdrdata[BEARER5SGWGTP_TEID]).append("|");
			sb.append(xdrdata[BEARER6ID]).append("|");
			sb.append(xdrdata[BEARER6TYPE]).append("|");
			sb.append(xdrdata[BEARER6QCI]).append("|");
			sb.append(xdrdata[BEARER6STATUS]).append("|");
			sb.append(xdrdata[BEARER6REQUESTCAUSE]).append("|");
			sb.append(xdrdata[BEARER6FAILURECAUSE]).append("|");
			sb.append(xdrdata[BEARER6ENBGTP_TEID]).append("|");
			sb.append(xdrdata[BEARER6SGWGTP_TEID]).append("|");
			sb.append(xdrdata[BEARER7ID]).append("|");
			sb.append(xdrdata[BEARER7TYPE]).append("|");
			sb.append(xdrdata[BEARER7QCI]).append("|");
			sb.append(xdrdata[BEARER7STATUS]).append("|");
			sb.append(xdrdata[BEARER7REQUESTCAUSE]).append("|");
			sb.append(xdrdata[BEARER7FAILURECAUSE]).append("|");
			sb.append(xdrdata[BEARER7ENBGTP_TEID]).append("|");
			sb.append(xdrdata[BEARER7SGWGTP_TEID]).append("|");
			sb.append(xdrdata[BEARER8ID]).append("|");
			sb.append(xdrdata[BEARER8TYPE]).append("|");
			sb.append(xdrdata[BEARER8QCI]).append("|");
			sb.append(xdrdata[BEARER8STATUS]).append("|");
			sb.append(xdrdata[BEARER8REQUESTCAUSE]).append("|");
			sb.append(xdrdata[BEARER8FAILURECAUSE]).append("|");
			sb.append(xdrdata[BEARER8ENBGTP_TEID]).append("|");
			sb.append(xdrdata[BEARER8SGWGTP_TEID]).append("|");
			sb.append(xdrdata[BEARER9ID]).append("|");
			sb.append(xdrdata[BEARER9TYPE]).append("|");
			sb.append(xdrdata[BEARER9QCI]).append("|");
			sb.append(xdrdata[BEARER9STATUS]).append("|");
			sb.append(xdrdata[BEARER9REQUESTCAUSE]).append("|");
			sb.append(xdrdata[BEARER9FAILURECAUSE]).append("|");
			sb.append(xdrdata[BEARER9ENBGTP_TEID]).append("|");
			sb.append(xdrdata[BEARER9SGWGTP_TEID]).append("|");
			list_zx.add(sb.toString());
		}
		return list_zx;
	}
}
