package com.boco.customer.fieldZx;

import java.util.ArrayList;
import java.util.List;
import java.util.regex.Pattern;

public class S1uDnsZx {
	private int TIME_ID=3;
	private int LENGTH=4;
	private int CITY=5;
	private int INTERFACE=6;
	private int XDR_ID=7;
	private int RAT=8;
	private int IMSI=9;
	private int IMEI=10;
	private int MSISDN=11;
	private int MACHINE_IP_ADD_TYPE=17;
	private int SGWIPADD=18;
	private int ENODEBIPADD=25;
	private int SGW_PORT=26;
	private int ENODEB_PORT=27;
	private int ENB_GTP_TEID=28;
	private int SGW_GTP_TEID=29;
	private int TAC=31;
	private int ECI=32;
	private int APN=30;
	private int APP_TYPE_CODE=48;
	private int START_TIME=49;
	private int END_TIME=50;
	private int PROTOCOL_TYPE=61;
	private int APP_TYPE=52;
	private int APP_SUB_TYPE=54;
	private int APP_CONTENT=60;
	private int APP_STATUS=64;
	private int USER_IPV4=65;
	private int USER_IPV6=66;
	private int USER_PORT=67;
	private int L4_PROTOCAL=68;
	private int APP_SERVER_IP_IPV4=69;
	private int APP_SERVER_IP_IPV6=70;
	private int APP_SERVER_PORT=71;
	private int UL_DATA=72;
	private int DL_DATA=73;
	private int UL_IP_PACKET=74;
	private int DL_IP_PACKET=75;
	private int UL_TCP_DISCORDNUM=76;
	private int DL_TCP_DISCORDNUM=77;
	private int UL_TCP_RENUM=78;
	private int DL_TCP_RENUM=79;
	private int TCP_RESPONSE_DELAY=82;
	private int TCP_CONFIRM_DELAY=83;
	private int UL_IP_FRAG_PACKETS=84;
	private int DL_IP_FRAG_PACKETS=85;
	private int TCP_SUCC_REQUEST_DELAY=86;
	private int FIRST_RESPONSE_DELAY=87;
	private int WINDOW_SIZE=86;
	private int MSS_SIZE=87;
	private int TCP_ATT_CNT=88;
	private int TCP_CONN_STATUS=89;
	private int SESSION_MARK_END =90;
	private int DNS_DESC=91;
	private int QUERY_IP=92;
	private int DNS_RESP_CODE=93;
	private int DNS_REQ_CNT=96;
	private int RESPONSE_CNT=97;
	private int AUTH_CONTENT_CNT=98;
	private int ADDI_CONTENT_CNT=99;
	private static Pattern pattern = Pattern.compile("\\|");
	public List<String> ReturnListZx(List<String> list)
	{
		
		List<String> list_zx =new ArrayList<String>();
		for(String lines:list)
		{
			
			String[] xdrdata = pattern.split(lines.toString(), -1);
			StringBuffer sb = new StringBuffer();
			 sb.append(xdrdata[TIME_ID]).append("|");
			sb.append(xdrdata[CITY]).append("|");
			sb.append(xdrdata[INTERFACE]).append("|");
			sb.append(xdrdata[XDR_ID]).append("|");
			sb.append(xdrdata[RAT]).append("|");
			sb.append(xdrdata[IMSI]).append("|");
			sb.append(xdrdata[IMEI]).append("|");
			sb.append(xdrdata[MSISDN]).append("|");
			sb.append(xdrdata[MACHINE_IP_ADD_TYPE]).append("|");
			sb.append(xdrdata[SGWIPADD]).append("|");
			sb.append(xdrdata[ENODEBIPADD]).append("|");
			sb.append(xdrdata[SGW_PORT]).append("|");
			sb.append(xdrdata[ENODEB_PORT]).append("|");
			sb.append(xdrdata[ENB_GTP_TEID]).append("|");
			sb.append(xdrdata[SGW_GTP_TEID]).append("|");
			sb.append(xdrdata[TAC]).append("|");
			sb.append(xdrdata[ECI]).append("|");
			sb.append(xdrdata[APN]).append("|");
			sb.append(xdrdata[APP_TYPE_CODE]).append("|");
			sb.append(xdrdata[START_TIME]).append("|");
			sb.append(xdrdata[END_TIME]).append("|");
			sb.append(xdrdata[PROTOCOL_TYPE]).append("|");
			sb.append(xdrdata[APP_TYPE]).append("|");
			sb.append(xdrdata[APP_SUB_TYPE]).append("|");
			sb.append(xdrdata[APP_CONTENT]).append("|");
			sb.append(xdrdata[APP_STATUS]).append("|");
			sb.append(xdrdata[USER_IPV4]).append("|");
			sb.append(xdrdata[USER_IPV6]).append("|");
			sb.append(xdrdata[USER_PORT]).append("|");
			sb.append(xdrdata[L4_PROTOCAL]).append("|");
			sb.append(xdrdata[APP_SERVER_IP_IPV4]).append("|");
			sb.append(xdrdata[APP_SERVER_IP_IPV6]).append("|");
			sb.append(xdrdata[APP_SERVER_PORT]).append("|");
			sb.append(xdrdata[UL_DATA]).append("|");
			sb.append(xdrdata[DL_DATA]).append("|");
			sb.append(xdrdata[UL_IP_PACKET]).append("|");
			sb.append(xdrdata[DL_IP_PACKET]).append("|");
			sb.append(xdrdata[UL_TCP_DISCORDNUM]).append("|");
			sb.append(xdrdata[DL_TCP_DISCORDNUM]).append("|");
			sb.append(xdrdata[UL_TCP_RENUM]).append("|");
			sb.append(xdrdata[DL_TCP_RENUM]).append("|");
			sb.append(xdrdata[TCP_RESPONSE_DELAY]).append("|");
			sb.append(xdrdata[TCP_CONFIRM_DELAY]).append("|");
			sb.append(xdrdata[UL_IP_FRAG_PACKETS]).append("|");
			sb.append(xdrdata[DL_IP_FRAG_PACKETS]).append("|");
			sb.append(xdrdata[TCP_SUCC_REQUEST_DELAY]).append("|");
			sb.append(xdrdata[FIRST_RESPONSE_DELAY]).append("|");
			sb.append(xdrdata[WINDOW_SIZE]).append("|");
			sb.append(xdrdata[MSS_SIZE]).append("|");
			sb.append(xdrdata[TCP_ATT_CNT]).append("|");
			sb.append(xdrdata[TCP_CONN_STATUS]).append("|");
			sb.append(xdrdata[SESSION_MARK_END]).append("|");
			sb.append(xdrdata[DNS_DESC]).append("|");
			sb.append(xdrdata[QUERY_IP]).append("|");
			sb.append(xdrdata[DNS_RESP_CODE]).append("|");
			sb.append(xdrdata[DNS_REQ_CNT]).append("|");
			sb.append(xdrdata[RESPONSE_CNT]).append("|");
			sb.append(xdrdata[AUTH_CONTENT_CNT]).append("|");
			sb.append(xdrdata[ADDI_CONTENT_CNT]).append("|");
			list_zx.add(sb.toString());
		}
		return list_zx;
	}
}
