package com.boco.customer.fieldJl;

public interface S1uS6a {
	int S1U_S6A_LEN = 26;
	int LENGTH=0;
	int CITY=1;
	int INTERFACE=2;
	int XDR_ID=3;
	int RAT=4;
	int IMSI=5;
	int IMEI=6;
	int MSISDN=7;
	int PROCEDURE_TYPE=8;
	int PROCEDURE_STRAT_TIME=9;
	int PROCEDURE_END_TIME=10;
	int PROCEDURE_STATUS=11;
	int CAUSE=12;
	int USER_IPV4=13;
	int USER_IPV6=14;
	int MME_ADDRESS=15;
	int HSS_ADDRESS=16;
	int MME_PORT=17;
	int HSS_PORT=18;
	int ORIGIN_REALM=19;
	int DESTINATION_REALM=20;
	int ORIGIN_HOST=21;
	int DESTINATION_HOST=22;
	int APPLICATION_ID=23;
	int SUBSCRIBER_STATUS=24;
	int ACCESS_RESTRICTION_DATA=25;
}

